defmodule DevpulseServer.Core.Repo.Migrations.AddSlugColumnToTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add(:slug, :text, null: false)
    end

    create(unique_index(:teams, [:slug], name: "teams_unique_slug_index"))
  end

  def down do
    drop_if_exists(unique_index(:teams, [:slug], name: "teams_unique_slug_index"))

    alter table(:teams) do
      remove(:slug)
    end
  end
end
