defmodule DevpulseServer.Core.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :text, null: false)
      add(:hashed_password, :text, null: false)
      add(:name, :text)
    end

    create table(:teams, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)

      add(
        :user_id,
        references(:users, column: :id, name: "teams_user_id_fkey", type: :uuid, prefix: "public")
      )
    end

    create table(:heartbeats, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:project_name, :text)
      add(:branch, :text)
      add(:repo_path, :text)
      add(:has_changes, :boolean)
      add(:agent_session_id, :uuid)
    end

    create table(:developer_profiles, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:email, :text, null: false)
      add(:avatar_url, :text)

      add(
        :team_id,
        references(:teams,
          column: :id,
          name: "developer_profiles_team_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:invite_id, :uuid)
    end

    create table(:developer_invites, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:developer_profiles) do
      modify(
        :invite_id,
        references(:developer_invites,
          column: :id,
          name: "developer_profiles_invite_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:developer_invites) do
      add(:email, :text, null: false)
      add(:token, :text, null: false)
      add(:status, :text, default: "pending")
      add(:expires_at, :utc_datetime)

      add(
        :team_id,
        references(:teams,
          column: :id,
          name: "developer_invites_team_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:api_tokens, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:token_hash, :text, null: false)
      add(:name, :text)
      add(:last_used_at, :utc_datetime)
      add(:revoked_at, :utc_datetime)

      add(
        :developer_profile_id,
        references(:developer_profiles,
          column: :id,
          name: "api_tokens_developer_profile_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:agent_sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:heartbeats) do
      modify(
        :agent_session_id,
        references(:agent_sessions,
          column: :id,
          name: "heartbeats_agent_session_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:agent_sessions) do
      add(:session_id, :text, null: false)
      add(:machine_name, :text)
      add(:last_seen_at, :utc_datetime)

      add(
        :developer_profile_id,
        references(:developer_profiles,
          column: :id,
          name: "agent_sessions_developer_profile_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:agent_sessions, "agent_sessions_developer_profile_id_fkey"))

    alter table(:agent_sessions) do
      remove(:developer_profile_id)
      remove(:last_seen_at)
      remove(:machine_name)
      remove(:session_id)
    end

    drop(constraint(:heartbeats, "heartbeats_agent_session_id_fkey"))

    alter table(:heartbeats) do
      modify(:agent_session_id, :uuid)
    end

    drop(table(:agent_sessions))

    drop(constraint(:api_tokens, "api_tokens_developer_profile_id_fkey"))

    drop(table(:api_tokens))

    drop(constraint(:developer_invites, "developer_invites_team_id_fkey"))

    alter table(:developer_invites) do
      remove(:team_id)
      remove(:expires_at)
      remove(:status)
      remove(:token)
      remove(:email)
    end

    drop(constraint(:developer_profiles, "developer_profiles_invite_id_fkey"))

    alter table(:developer_profiles) do
      modify(:invite_id, :uuid)
    end

    drop(table(:developer_invites))

    drop(constraint(:developer_profiles, "developer_profiles_team_id_fkey"))

    drop(table(:developer_profiles))

    drop(table(:heartbeats))

    drop(constraint(:teams, "teams_user_id_fkey"))

    drop(table(:teams))

    drop(table(:users))
  end
end
