defmodule :"Elixir.DevpulseServer.Core.Repo.Migrations.Refactor-agent-and-user-resource-ownwership" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:teams), :user_id, to: :organization_id)

    drop(constraint(:teams, "teams_user_id_fkey"))

    alter table(:teams) do
      modify(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "teams_organization_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:projects, [:team_id, :name], name: "projects_unique_team_project_name_index")
    )

    alter table(:organizations) do
      add(
        :user_id,
        references(:users,
          column: :id,
          name: "organizations_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    alter table(:heartbeats) do
      remove(:team_id)
    end

    drop(constraint(:agent_sessions, "agent_sessions_team_id_fkey"))

    drop_if_exists(
      unique_index(:agent_sessions, [:developer_profile_id, :team_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    rename(table(:agent_sessions), :team_id, to: :project_id)

    create(
      unique_index(:agent_sessions, [:developer_profile_id, :project_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    alter table(:agent_sessions) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          name: "agent_sessions_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:agent_sessions, "agent_sessions_project_id_fkey"))

    alter table(:agent_sessions) do
      modify(
        :project_id,
        references(:teams,
          column: :id,
          name: "agent_sessions_team_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: true)
    end

    drop_if_exists(
      unique_index(:agent_sessions, [:developer_profile_id, :project_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    rename(table(:agent_sessions), :project_id, to: :team_id)

    create(
      unique_index(:agent_sessions, [:developer_profile_id, :team_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    alter table(:heartbeats) do
      add(
        :team_id,
        references(:teams,
          column: :id,
          name: "heartbeats_team_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:organizations, "organizations_user_id_fkey"))

    alter table(:organizations) do
      remove(:user_id)
    end

    drop_if_exists(
      unique_index(:projects, [:team_id, :name], name: "projects_unique_team_project_name_index")
    )

    drop(constraint(:teams, "teams_organization_id_fkey"))

    alter table(:teams) do
      modify(
        :organization_id,
        references(:users,
          column: :id,
          name: "teams_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: true)
    end

    rename(table(:teams), :organization_id, to: :user_id)
  end
end
