defmodule DevpulseServer.Core.Repo.Migrations.AddProjectAndSessionToHeartbeats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(unique_index(:teams, [:slug], name: "teams_unique_slug_index"))

    drop_if_exists(constraint(:heartbeats, "heartbeats_agent_session_id_fkey"))

    create(unique_index(:teams, [:organization_id, :slug], name: "teams_unique_slug_index"))

    create(unique_index(:organizations, [:slug], name: "organizations_unique_slug_index"))

    drop_if_exists(constraint(:heartbeats, "heartbeats_session_id_fkey"))

    alter table(:heartbeats) do
      remove(:agent_session_id)

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "heartbeats_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      modify(
        :session_id,
        references(:agent_sessions,
          column: :id,
          name: "heartbeats_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:developer_invites, [:token], name: "developer_invites_unique_token_index")
    )
  end

  def down do
    drop_if_exists(
      unique_index(:developer_invites, [:token], name: "developer_invites_unique_token_index")
    )

    drop(constraint(:heartbeats, "heartbeats_project_id_fkey"))

    drop(constraint(:heartbeats, "heartbeats_session_id_fkey"))

    alter table(:heartbeats) do
      add(
        :agent_session_id,
        references(:agent_sessions,
          column: :id,
          name: "heartbeats_agent_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      modify(
        :session_id,
        references(:agent_sessions,
          column: :id,
          name: "heartbeats_agent_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: true
      )

      remove(:project_id)
    end

    rename(table(:heartbeats), :session_id, to: :agent_session_id)

    drop_if_exists(unique_index(:organizations, [:slug], name: "organizations_unique_slug_index"))

    drop_if_exists(
      unique_index(:teams, [:organization_id, :slug], name: "teams_unique_slug_index")
    )

    create(unique_index(:teams, [:slug], name: "teams_unique_slug_index"))
  end
end
