defmodule DevpulseServer.Core.Repo.Migrations.IntroduceMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_memberships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :team_id,
        references(:teams,
          column: :id,
          name: "team_memberships_team_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :developer_profile_id,
        references(:developer_profiles,
          column: :id,
          name: "team_memberships_developer_profile_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:team_memberships, [:team_id, :developer_profile_id],
        name: "team_memberships_unique_team_membership_index"
      )
    )

    create table(:organizations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:slug, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "organizations_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(unique_index(:organizations, [:slug]))

    create(unique_index(:organizations, [:name]))

    alter table(:heartbeats) do
      add(
        :session_id,
        references(:agent_sessions,
          column: :id,
          name: "heartbeats_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    alter table(:developer_profiles) do
      remove(:team_id)
    end

    create(
      unique_index(:developer_profiles, [:email], name: "developer_profiles_unique_email_index")
    )

    drop_if_exists(
      unique_index(:agent_sessions, [:developer_profile_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    alter table(:agent_sessions) do
      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "agent_sessions_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:agent_sessions, [:developer_profile_id, :project_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )
  end

  def down do
    drop(constraint(:agent_sessions, "agent_sessions_team_id_fkey"))

    drop_if_exists(
      unique_index(:agent_sessions, [:developer_profile_id, :project_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    create(
      unique_index(:agent_sessions, [:developer_profile_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    alter table(:agent_sessions) do
      remove(:team_id)
    end

    rename(table(:agent_sessions), :hostname, to: :machine_name)

    drop_if_exists(
      unique_index(:developer_profiles, [:email], name: "developer_profiles_unique_email_index")
    )

    alter table(:developer_profiles) do
      remove(:updated_at)
      remove(:inserted_at)

      add(
        :team_id,
        references(:teams,
          column: :id,
          name: "developer_profiles_team_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:heartbeats, "heartbeats_team_id_fkey"))

    alter table(:heartbeats) do
      remove(:team_id)
    end

    drop(table(:organizations))

    drop(constraint(:team_memberships, "team_memberships_team_id_fkey"))

    drop(constraint(:team_memberships, "team_memberships_developer_profile_id_fkey"))

    drop_if_exists(
      unique_index(:team_memberships, [:team_id, :developer_profile_id],
        name: "team_memberships_unique_team_membership_index"
      )
    )

    drop(table(:team_memberships))
  end
end
