defmodule DevpulseServer.Core.Repo.Migrations.AddProjectsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:git_remote_url, :text, null: false)

      add(
        :team_id,
        references(:teams,
          column: :id,
          name: "projects_team_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(unique_index(:projects, [:git_remote_url], name: "projects_unique_git_remote_index"))

    alter table(:agent_sessions) do
      remove(:last_seen_at)
      remove(:session_id)
      modify(:developer_profile_id, :uuid, null: false)
      add(:computer_identifier, :text, null: false)
      add(:os, :text)

      add(
        :api_token_id,
        references(:api_tokens,
          column: :id,
          name: "agent_sessions_api_token_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:agent_sessions, [:developer_profile_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )
  end

  def down do
    drop(constraint(:agent_sessions, "agent_sessions_api_token_id_fkey"))

    drop_if_exists(
      unique_index(:agent_sessions, [:developer_profile_id, :computer_identifier],
        name: "agent_sessions_unique_computer_session_index"
      )
    )

    alter table(:agent_sessions) do
      remove(:api_token_id)
      remove(:os)
      remove(:computer_identifier)
      modify(:developer_profile_id, :uuid, null: true)
      add(:session_id, :text, null: false)
      add(:last_seen_at, :utc_datetime)
    end

    drop(constraint(:projects, "projects_team_id_fkey"))

    drop_if_exists(
      unique_index(:projects, [:git_remote_url], name: "projects_unique_git_remote_index")
    )

    drop(table(:projects))
  end
end
