defmodule DevpulseServer.Core.Repo.Migrations.AddLastSeenColumnToAgentSession do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:heartbeats) do
      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    alter table(:agent_sessions) do
      add(:last_seen_at, :utc_datetime, null: false)
    end
  end

  def down do
    alter table(:agent_sessions) do
      remove(:last_seen_at)
    end

    alter table(:heartbeats) do
      remove(:inserted_at)
    end
  end
end
